<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>

<script setup>
import "vue3-marquee/dist/style.css";

const query = groq`*[_type == "post"]`;
const { data } = await useSanityQuery(query);
console.log(data);
</script>

<style>
/* NOTE: found this selector by looking at the inspector. i assume div that is generated by NuxtLayout or NuxtPage. */
/* #__nuxt {
  font-family: "Spartan", sans-serif;
} */
</style>

